// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhC2dgQ6aC2dxA-VAG7OPqAsFCsP9Ab3c',
    appId: '1:706633074898:web:658fb96c76ce177aec450b',
    messagingSenderId: '706633074898',
    projectId: 'testtruereaction',
    authDomain: 'testtruereaction.firebaseapp.com',
    storageBucket: 'testtruereaction.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdDLlptwpRUyw-z_9p6qTUJbaNVuqWPy4',
    appId: '1:706633074898:android:2762d345b25a71ebec450b',
    messagingSenderId: '706633074898',
    projectId: 'testtruereaction',
    storageBucket: 'testtruereaction.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUMGfnvvvTdBOaw6mZhav6o5UzrpmGUm8',
    appId: '1:706633074898:ios:57528b236de41bccec450b',
    messagingSenderId: '706633074898',
    projectId: 'testtruereaction',
    storageBucket: 'testtruereaction.firebasestorage.app',
    iosBundleId: 'com.example.testTruereaction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUMGfnvvvTdBOaw6mZhav6o5UzrpmGUm8',
    appId: '1:706633074898:ios:57528b236de41bccec450b',
    messagingSenderId: '706633074898',
    projectId: 'testtruereaction',
    storageBucket: 'testtruereaction.firebasestorage.app',
    iosBundleId: 'com.example.testTruereaction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhC2dgQ6aC2dxA-VAG7OPqAsFCsP9Ab3c',
    appId: '1:706633074898:web:40a7a290e4d6ce24ec450b',
    messagingSenderId: '706633074898',
    projectId: 'testtruereaction',
    authDomain: 'testtruereaction.firebaseapp.com',
    storageBucket: 'testtruereaction.firebasestorage.app',
  );
}
