// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnmNzgkoFNKRKCC7ox_4nzqGskz2iPOz0',
    appId: '1:813458560199:web:d5beef2f7cfd4cab3cdae2',
    messagingSenderId: '813458560199',
    projectId: 'glacier-eb589',
    authDomain: 'glacier-eb589.firebaseapp.com',
    storageBucket: 'glacier-eb589.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5CLWgtagULAqebU_QmgG-vsZBtqPufmM',
    appId: '1:813458560199:android:2acf114e927f0f9c3cdae2',
    messagingSenderId: '813458560199',
    projectId: 'glacier-eb589',
    storageBucket: 'glacier-eb589.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxjvXM8Hbd17OYmt9Y5bqtWXmOBVFxhk0',
    appId: '1:813458560199:ios:cf700fee1130fe013cdae2',
    messagingSenderId: '813458560199',
    projectId: 'glacier-eb589',
    storageBucket: 'glacier-eb589.firebasestorage.app',
    iosBundleId: 'com.tryglacier.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxjvXM8Hbd17OYmt9Y5bqtWXmOBVFxhk0',
    appId: '1:813458560199:ios:cf700fee1130fe013cdae2',
    messagingSenderId: '813458560199',
    projectId: 'glacier-eb589',
    storageBucket: 'glacier-eb589.firebasestorage.app',
    iosBundleId: 'com.tryglacier.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnmNzgkoFNKRKCC7ox_4nzqGskz2iPOz0',
    appId: '1:813458560199:web:a7bf7d27eb48e8e43cdae2',
    messagingSenderId: '813458560199',
    projectId: 'glacier-eb589',
    authDomain: 'glacier-eb589.firebaseapp.com',
    storageBucket: 'glacier-eb589.firebasestorage.app',
  );

}